version: '3.6'
services:
  mongo:
    container_name: ll_mongo
    image: mongo:4.0
    # ports:
    # - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: learninglocker_v2
    volumes:
    - mongo-config:/data/configdb:rw
    - mongo-data:/data/db:rw
  redis:
    # activate persistency
    command: redis-server --appendonly yes
    container_name: ll_redis
    image: redis:4.0
    # ports:
    # - 6379:6379
    volumes:
    - redis-data:/data:rw
  xapi:
    # activate persistency
    container_name: ll_xapi
    image: learninglocker/xapi-service:latest
    ports:
    - 8081:8081
    env_file: .env.xapi
    links:
    - redis:redis
    - mongo:mongo
    depends_on:
    - redis
    - mongo
  lrs:
    # activate persistency
    container_name: ll_lrs
    image: aiwin/learninglocker:latest
    ports:
    - 8080:8080
    - 3000:3000
    env_file: .env.ll
    links:
    - redis:redis
    - mongo:mongo
    depends_on:
    - redis
    - mongo

volumes:
  mongo-config: {}
  mongo-data: {}
  redis-data: {}